### ISSUE TITLE
Decouple CLI to the separate project

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/tracey-protocol-eiffel#1]

**Comment by MadsNielsen** [comment]
Done

**Comment by Andrey9kin** [comment]
@MadsNielsen where is it done? I mean that we need to decouple generator from the cli wrapper. So most probably it will be one more repo

**Comment by MadsNielsen** [comment]
@Andrey9kin Ahh i think i misunderstood this one. Are you thinking about the cli to generate eiffel messages? 

The cli currenly only has one implementation (The rabbitmq implementation). I think we can wait abit before renaming the current cli to a rabbitmq-tracey-cli repo. Atleast until we need to make it wrap another type of messaging middleware.
